services:
  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html # :ro mean read only
    # Only need to expose ports to access nginx on host machine,
    # mainly for development. Cloudflared can always access it.
      - ./db:/usr/share/nginx/html/db:ro
    ports:
      - 80:80
      - 443:443
      - 8000:8000
  rock:
    build:
      context: ./rock4cplus
      dockerfile: Dockerfile
    working_dir: /rock4cplus
    # Feels bad, but recommended solution
    command: >
      sh -c "digitemp_DS9097 -i -s /dev/ttyUSB0
      && node --watch logger.js"
    volumes:
      # Should probably move logger.js to src folder,
      # then just mount the whole folder.
      # Because now you have to add each file you create.
      # Or add a dockerignore or something. IDK
      - ./rock4cplus/logger.js:/rock4cplus/logger.js
      - ./db:/rock4cplus/db
    # Just comment out devices if you are missing USBtemp
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
