services:
  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro # :ro mean read only
    ports:
      - 80:80
      - 443:443
      - 8000:8000
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx
